name: Devlo.ai Code Review

on:
  workflow_dispatch:
    inputs:
      review_guidelines:
        description: "Guidelines to follow during the review"
        required: false
        default: |
          - Follow the OpenHAB Developer Guide: https://www.openhab.org/docs/developer/
          - Subtopics: Coding Guidelines, Testing, Add-ons, Contribution Workflow, etc.
          - Focus: Developing an OpenHAB binding for the LinkPlay API.
          - LinkPlay API documentation: https://developer.arylic.com/httpapi/#http-api.
          - Ensure adherence to OpenHAB coding and testing standards.

  pull_request:
    paths:
      - 'bundles/org.openhab.binding.linkplay/**'
    branches:
      - linkplay-4.3.x

  push:
    paths:
      - 'bundles/org.openhab.binding.linkplay/**'
    branches:
      - linkplay-4.3.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Devlo.ai Code Review
        env:
          OPENHAB_GUIDELINES: |
            Follow the OpenHAB Developer Guide: https://www.openhab.org/docs/developer/
            Subtopics: Coding Guidelines, Testing, Add-ons, Contribution Workflow, etc.
            Focus: Developing an OpenHAB binding for the LinkPlay API.
            LinkPlay API documentation: https://developer.arylic.com/httpapi/#http-api.
            Ensure adherence to OpenHAB coding and testing standards.
        run: |
          echo "Providing guidelines to Devlo.ai:"
          echo "$OPENHAB_GUIDELINES"
          # Replace the following with the actual Devlo.ai command if needed
          devloai review --directory "bundles/org.openhab.binding.linkplay" --guidelines "$OPENHAB_GUIDELINES"
