name: Devlo.ai Code Review

on:
  workflow_dispatch: # Enables manual triggering
  pull_request:
    paths:
      - 'bundles/org.openhab.binding.linkplay/**'
    branches:
      - linkplay-4.3.x
  push:
    paths:
      - 'bundles/org.openhab.binding.linkplay/**'
    branches:
      - linkplay-4.3.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Devlo.ai Code Review
        run: echo "Running Devlo.ai code review!"
